// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5DS1Y_L82eJxdTPBlml1svYmkYX4I18A',
    appId: '1:1029557359685:web:4f2d44bced1b6321f9ff2c',
    messagingSenderId: '1029557359685',
    projectId: 'hapticfone-ff0c4',
    authDomain: 'hapticfone-ff0c4.firebaseapp.com',
    storageBucket: 'hapticfone-ff0c4.firebasestorage.app',
    measurementId: 'G-NVX0QTB377',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6RS9BxgT7E8BQT0KX3GucpkAn1MJlBs',
    appId: '1:1029557359685:android:c206d92639df6030f9ff2c',
    messagingSenderId: '1029557359685',
    projectId: 'hapticfone-ff0c4',
    storageBucket: 'hapticfone-ff0c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhS3KSsplZ99qhWtlzVDzD1W4HR3hzwFI',
    appId: '1:1029557359685:ios:ded37419053f681ff9ff2c',
    messagingSenderId: '1029557359685',
    projectId: 'hapticfone-ff0c4',
    storageBucket: 'hapticfone-ff0c4.firebasestorage.app',
    androidClientId:
        '1029557359685-9ejeq9aj38fck1i62shedvlh891o4t1i.apps.googleusercontent.com',
    iosClientId:
        '1029557359685-35b8u8c0shcd8688d3kmo6kq6ejmkhos.apps.googleusercontent.com',
    iosBundleId: 'com.example.hapticfone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhS3KSsplZ99qhWtlzVDzD1W4HR3hzwFI',
    appId: '1:1029557359685:ios:ded37419053f681ff9ff2c',
    messagingSenderId: '1029557359685',
    projectId: 'hapticfone-ff0c4',
    storageBucket: 'hapticfone-ff0c4.firebasestorage.app',
    androidClientId:
        '1029557359685-9ejeq9aj38fck1i62shedvlh891o4t1i.apps.googleusercontent.com',
    iosClientId:
        '1029557359685-35b8u8c0shcd8688d3kmo6kq6ejmkhos.apps.googleusercontent.com',
    iosBundleId: 'com.example.hapticfone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5DS1Y_L82eJxdTPBlml1svYmkYX4I18A',
    appId: '1:1029557359685:web:535d67ee9106974df9ff2c',
    messagingSenderId: '1029557359685',
    projectId: 'hapticfone-ff0c4',
    authDomain: 'hapticfone-ff0c4.firebaseapp.com',
    storageBucket: 'hapticfone-ff0c4.firebasestorage.app',
    measurementId: 'G-NPW53961D7',
  );
}
